name: parsing-recipe
version: 0.1.0.0
github: "gregorias/parsing-recipe"
license: AGPL-3
author: "Grzegorz Milka"
maintainer: "grzegorzmilka@gmail.com"
copyright: "Copyright (c) 2023 Grzegorz Milka"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/gregorias/parsing-recipe#readme>

language: GHC2021

default-extensions:
  - DataKinds
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiWayIf
  # Prefer using the safer option like Relude.
  - NoImplicitPrelude
  - OverloadedLabels
  - OverloadedRecordDot
  - OverloadedStrings
  - TypeFamilies
  - TypeOperators

dependencies:
  - base >= 4.17 && < 5
  - relude

# no-type-defaults, this is dangerous, but in terms of convenience it's so
# useful to use ExtendedDefaultRules that I keep it.
#
# no-name-shadowing: Name shadowing is potentially dangerous, but not having it
# forces me to figure out alternative names, which can make code less readable.
# Overall, I think it's worth the trade off to enable name shadowing.
ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Wmissing-deriving-strategies
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-type-defaults
  - -Wno-partial-type-signatures
  - -Wno-name-shadowing

library:
  source-dirs: src
  ghc-options:
    - -Wunused-packages
  dependencies:
    - barbies
    - extra
    - megaparsec
    - time

tests:
  parsing-recipe-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      # - -Wunused-packages
    dependencies:
      - barbies
      - hspec
      - hspec-expectations-pretty-diff
      - megaparsec
      - parsing-recipe
      - time
